databases:
  - name: app_database
    databaseName: app_prod
    user: app_db
    plan: free

services:
  - type: redis
    name: redis-sidekiq
    plan: free
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: []
  - type: web
    name: app_web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s -d -p 10000 & bundle exec sidekiq -q default
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-sidekiq
          property: connectionString
      - key: PORT
        value: 10000
