default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= Rails.application.credentials.dig(:postgres, :local, :user) %>
  password: <%= Rails.application.credentials.dig(:postgres, :local, :password) %>
  timeout: 5000

development:
  <<: *default
  database: storage/development_postgresql

test:
  <<: *default
  database: storage/test_postgresql

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
